# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'node_modules/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: true
Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines
